### ISSUE TITLE
 建议

### ISSUE THREAD

**Issue by lany9527** [ProtoTeam/i18n-pick#3]
# 建议：
### 这样替换以后项目文件可读性会好点，这样scan和pick后，效果如下：

![image](https://user-images.githubusercontent.com/19483798/31977488-bc80a2fe-b96f-11e7-8d28-5d73cd0974fa.png)

##### 再配合 atool-l10n翻译后效果如下：

![image](https://user-images.githubusercontent.com/19483798/31977656-6fc0ac06-b970-11e7-8fdc-a87bb3cbf168.png)

**Comment by panyifei** [comment]
明白了，你是想用中文作为key值。这样子的可读性确实比注释更好一些。

但是我的担心是如果中文词条过多过长，en.json会过大，而且这些字符串内容编译的时候是无法被压缩的。

所以我选择将中文词条作为注释放在末尾，这样编译压缩之后的上线代码就会丢弃掉注释。内容就会少一些，而且也有一定的可读性。

**Comment by lany9527** [comment]
你说的也是，但是团队合作的话，数字作为key有点难以接受。我fork了你的代码，改了一点。谢谢你的idea，提高了生产效率。有个问题就是扫描的时候每次都要把之前的扫描文件夹先删掉，不然会报错。

**Comment by panyifei** [comment]
是的，数字作为key，确实没法接受，中文作为key，还能复用，虽然uglify没法压缩，但是gzip也能够压缩。要不你提个pr?

**Comment by panyifei** [comment]
我自己修复了哈，多谢你的建议~~

**Comment by huyansheng3** [comment]
柯南 和 基德。。
