### ISSUE TITLE
'base/reactIntlUniversal问题

### ISSUE THREAD

**Issue by lany9527** [ProtoTeam/i18n-pick#4]
### (｡･∀･)ﾉﾞ嗨 'base/reactIntlUniversal'怎么不一起提供呢.我想看看封装原理.我很好奇reactIntlUniversal这个是不是可以实现无刷新切换多语言.因为我觉得 react-intl-universal 需要刷新页面切换语言不太友好.

**Comment by panyifei** [comment]
也得刷新页面的，因为没有通过props传进去，刷新页面是个低频操作，我这里觉得是可以容忍的
